### ISSUE TITLE
Keep devel and v5.x branches in sync with master branch

### ISSUE THREAD

**Issue by seisman** [conda-forge/gmt-feedstock#112]
The conda-forge's bots can make commits and PRs to the master branch, but don't change anything in the devel and v5.x branches. I believe we have to manually update these branches to keep in sync with the master branch.

**Comment by ocefpaf** [comment]
There is an experimental support branches now. @beckermr can probably guide you on how to use it.

**Comment by beckermr** [comment]
See the documentation here: https://regro.github.io/cf-scripts/migrators.html#migrating-branches-on-your-feedstock

If you have trouble or think you are not getting a PR you should, let us know! You will probably be the first people to use this!

**Comment by seisman** [comment]
Will we get PRs for previous migrations? Or the changes in #115 only work for future migrations?

**Comment by beckermr** [comment]
It should get prs for any ongoing migrations that apply. If it doesn't, we have a bug. This is experimental so bugs are to be expected.

**Comment by seisman** [comment]
OK. Let's wait for a few more days.

**Comment by beckermr** [comment]
We fixed one bug. Which migrations were you expecting?

**Comment by seisman** [comment]
> Which migrations were you expecting?

The recent gdal31 and hdf5 migrations.

**Comment by beckermr** [comment]
All of these PRs have been issued. The bot ignores branch PRs when figuring out whether or not to move on in a migration, so merge when you have time to debug them.

**Comment by seisman** [comment]
Great! Thanks.

**Comment by leouieda** [comment]
Thanks for all the help @beckermr! PRs actually went much smoother on `devel`.

**Comment by seisman** [comment]
All done! Thanks for the help from @beckermr again.
