### ISSUE TITLE
Build with OpenMP enabled?

### ISSUE THREAD

**Issue by weiji14** [conda-forge/gmt-feedstock#262]
### Comment:

Certain modules in GMT like [grdimage](https://docs.generic-mapping-tools.org/6.4/grdimage.html) support running on multiple CPU cores via the [`-x`](https://docs.generic-mapping-tools.org/6.4/cookbook/options.html?#option-x-core) option, but the current conda-forge stable build of GMT (6.4.0 hc1d54ec_12) is not compiled with [OpenMP](https://en.wikipedia.org/wiki/OpenMP) so it is not enabled.

To test, follow https://docs.generic-mapping-tools.org/6.4/gmt-config.html?highlight=openmp and run `gmt-config --has-openmp` which currently prints `no`.

Opening this issue to track progress. I think we'll need to add a `-D GMT_ENABLE_OPENMP=TRUE` flag to the build step here https://github.com/conda-forge/gmt-feedstock/blob/2a7a1810e522c42c3aefadda0f71ab51e178d682/recipe/build.sh#L17-L33 and maybe add a dependency on one of the openmp variants?

**Comment by seisman** [comment]
> maybe add a dependency on one of the openmp variants?

I think it's not necessary.

**Comment by weiji14** [comment]
Ok, let's test it out, opened PR at #263 for GMT 6.4. Can also add it for GMT 6.5 dev builds. Not sure if we should enable it on GMT 5.x?

**Comment by weiji14** [comment]
Cool, build 14 on https://anaconda.org/conda-forge/gmt/files?version=6.4.0 now has OpenMP and Glib Gthread enabled :tada: . Should be able to install it with `mamba install gmt=6.4.0=hb5fd6f7_14` for Linux, but am getting a conflict with the GEOS version Shapely is using, need to wait for https://github.com/conda-forge/shapely-feedstock/pull/125.

I'll work on applying #263 to the GMT 6.5 dev build. Do you want to add it to the `v5.x` branch @seisman? Or should we leave it?

**Comment by seisman** [comment]
> Do you want to add it to the `v5.x` branch @seisman? Or should we leave it?

I don't think we should add any new features (i.e., OpenMP support) to the GMT5 builds, so let's leave as it is.
