### ISSUE TITLE
Feature request: add GMT to conda-forge/linux-aarch64

### ISSUE THREAD

**Issue by yebo-liu** [conda-forge/gmt-feedstock#273]
Hi,

I’m trying to install GMT in a Docker image. However, conda/mamba don’t seem to be able to find gmt.

My environment is a Macbook with a M2 Max chip.

Error message:

![image](https://github.com/conda-forge/gmt-feedstock/assets/56617247/4c6bf9dd-4625-45c2-bebc-fc72b6255d1f)

Steps to reproduce the problem:
docker run -it --rm -p 8888:8888 -v ${PWD}:/home condaforge/mambaforge:latest
mamba install gmt

I guess this problem is because gmt is not available in conda-forge/linux-aarch64 or conda-forge/noarch? Is it possible to add gmt there?

Thanks

**Comment by seisman** [comment]
@ocefpaf Could you please provide some guides about how to enable linux-aarch64 build for this package?

I found some documentation that may be related:

- https://conda-forge.org/docs/maintainer/conda_forge_yml.html#build-platform
- https://conda-forge.org/docs/maintainer/conda_forge_yml.html#provider

Or maybe I should directly update https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt like what this PR https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4735 did?

**Comment by weiji14** [comment]
> Or maybe I should directly update https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt like what this PR conda-forge/conda-forge-pinning-feedstock#4735 did?

Yes, we'll need to add gmt to that file, which would trigger an aarch-64 migration. Note though that all of gmt's dependencies o conda-forge would also need to have aarch-64 builds (which is handled by the migration bot I think), so it might take some time.

**Comment by seisman** [comment]
> That said, is the M2 Max chip not using the OSX Arm builds (added in #199)?

The OP was trying to install GMT in a Docker image. From what I know about docker, the image can only be Linux.

**Comment by weiji14** [comment]
> > That said, is the M2 Max chip not using the OSX Arm builds (added in #199)?
> 
> The OP was trying to install GMT in a Docker image. From what I know about docker, the image can only be Linux.

Hmm, I see that Mambaforge has OSX-arm64 (see https://github.com/conda-forge/miniforge/tree/23.3.1-1#mambaforge), and there should be a way to build darwin/arm64 builds for docker (https://docs.docker.com/build/building/multi-platform)? But Mambaforge only uploads docker builds for linux arm64/amd64/ppc64le at https://hub.docker.com/layers/condaforge/mambaforge/23.3.1-1/images/sha256-7ccbb74f731fda573da8cb45499f3889d3469de523397b44a5e46edf4ca8192b?context=explore, so won't work I guess.

I've started a PR for the aarch64 migration at https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5185. Once that is merged, we can track the status at https://conda-forge.org/status/#aarch64andppc64leaddition

**Comment by weiji14** [comment]
Ok, that was easy, looks like we just need https://github.com/conda-forge/dcw-gmt-feedstock/pull/12 and https://github.com/conda-forge/gshhg-gmt-feedstock/pull/8

![image](https://github.com/conda-forge/gmt-feedstock/assets/23487320/0bb641c9-aee0-433c-b6ff-2028b35fb5dc)

**Comment by seisman** [comment]
dcw and gshhg are just data files and are arch-independent. Is it possible setting it to `noarch` so it's available on all platforms?

**Comment by weiji14** [comment]
> dcw and gshhg are just data files and are arch-independent. Is it possible setting it to `noarch` so it's available on all platforms?

Yes, that might be better actually. See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-generic.

**Comment by ocefpaf** [comment]
These data packages have some differences in the install directories on Windows and non-Windows. We can probably do a OS-noarch in that case.

**Comment by seisman** [comment]
@yebo-liu GMT should be available on the conda-forge/linux-aarch64 channel. Please check if it works for you.

**Comment by yebo-liu** [comment]
Just tested. I can successfully install GMT in the aarch64 based docker image now. Thanks!
