### ISSUE TITLE
Add support for ARM (e.g., Asahi Linux on Apple hardware)

### ISSUE THREAD

**Issue by MarkWieczorek** [conda-forge/gmt-feedstock#276]
### Comment:

After installing [Asahi Linux](https://asahilinux.org/) on an M1 Apple computer, there was only 1 scientific conda package that I use that wouldn't install: gmt (and by consequence [pygmt](https://github.com/conda-forge/pygmt-feedstock)). Would it be possible to add ARM support for this package?

Though there might not have been much interest in ARM support before, as Asahi Linux approaches an official release, this will certainly change. For info, here is what a mamba install outputs:

```
Could not solve for environment specs
The following packages are incompatible
└─ pygmt   is uninstallable because there are no viable options
   ├─ pygmt [0.2.1|0.3.0|0.3.1] would require
   │  └─ gmt >=6.1.1,<7.0 , which does not exist (perhaps a missing channel);
   ├─ pygmt [0.4.0|0.4.1|0.5.0] would require
   │  └─ gmt >=6.2.0,<7.0 , which does not exist (perhaps a missing channel);
   └─ pygmt [0.10.0|0.6.0|...|0.9.0] would require
      └─ gmt >=6.3.0,<7.0 , which does not exist (perhaps a missing channel).
```

**Comment by MarkWieczorek** [comment]
Maybe? If aarch64 is what runs on apple hardware, then I'll test it when its ready!

**Comment by seisman** [comment]
@MarkWieczorek GMT is now available on the conda-forge/linux-aarch64 channel. Could you please check if it solves your problem?

**Comment by MarkWieczorek** [comment]
It works! Thanks!
