### ISSUE TITLE
[GMT6] libgfortran warning (relink with librt)

### ISSUE THREAD

**Issue by paride** [conda-forge/gmt-feedstock#36]
Every time I start gmt 6 (installed from the dev channel) I get this warning:
```
gmt: Relink `/home/pl/miniconda3/envs/sismo/bin/../lib/./libgfortran.so.3' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
```
I'm not sure about what the implications are. These are the `libgfortran` packages I have installed:
```
$ conda list gfortran
# packages in environment at /home/pl/miniconda3/envs/sismo:
#
libgfortran               3.0.0                         1
libgfortran-ng            7.2.0                h9f7466a_2
```
Perhaps GMT should be linked against `libgfortran-ng`?

**Comment by leouieda** [comment]
Hi @paride, thanks for reporting. I'm not sure why GMT is linking against libgfortran in the first place. Are you having any problems with the plots?

**Comment by paride** [comment]
I'm just plotting very simple things at the moment (not even geographical maps for the moment), but it seems to work fine. I guess from your answer that you are not getting the warning, is it right?

**Comment by leouieda** [comment]
I'm not. But if it's not causing problems then I guess you can ignore it. I tried reproducing it by  installing the libgfortran that you report but got nothing.

**Comment by paride** [comment]
Issue disappeared by upgrading.

**Comment by leouieda** [comment]
@paride thanks for reporting
