### ISSUE TITLE
Delete the 6.0.0 alpha builds from the main channel

### ISSUE THREAD

**Issue by leouieda** [conda-forge/gmt-feedstock#63]
For some reason, some of the 6.0.0a* builds ended up in the `main` channel and are causing trouble for some users. We need to delete those.

**Comment by leouieda** [comment]
@ocefpaf is there a way to delete packages from the Anaconda cloud?

**Comment by ocefpaf** [comment]
Done! Let me know if I missed anything.
(It takes ~30 min for the channel to update, so give it some time before you test it.)

**Comment by leouieda** [comment]
Thanks @ocefpaf! Works perfectly. No need to delete them if they're not on the main channel.
