### ISSUE TITLE
GMT 6.0.0rc3 fails on macOS due to network connection issue

### ISSUE THREAD

**Issue by seisman** [conda-forge/gmt-feedstock#75]
We need to restart the macOS build.

**Comment by leouieda** [comment]
:disappointed:

**Comment by ocefpaf** [comment]
Restarting with Azure is terrible at the moment. Our "trick" is to push an empty commit to `master` with: `git commit --amend --no-edit && git push --force`

**Comment by seisman** [comment]
This will rewrite the git history. Maybe it's better to increase the build number.

**Comment by ocefpaf** [comment]
> This will rewrite the git history.

Nope. It is an empty commit. Same history.

> Maybe it's better to increase the build number.

Nope. We prefer to reserve build number bumps to functional changes.

Please see the note in https://conda-forge.org/docs/maintainer/adding_pkgs.html#adding-multiple-packages-at-once (it is the same problem, re-starting CIs.)
