### ISSUE TITLE
Branch model after 6.0.0 is released

### ISSUE THREAD

**Issue by seisman** [conda-forge/gmt-feedstock#81]
The official 6.0.0 version will be released in next several days. After 6.0.0 is out, we need to merge the dev branch into master branch. 

As the GMT team may still maintain GMT5 for a while, it would be good if conda-forge can provide both GMT5 and GMT6 (GMT6 by default). Thus we need to move GMT5 to another branch, e.g. `gmt5`, so users can install GMT6 by:
```
conda install gmt
```

and GMT5 by:
```
conda install -c conda-forge/label/gmt5 gmt
```

**Comment by ocefpaf** [comment]
@seisman no need to merge the dev branch into master. Just update the recipe accordingly and re-render. We can create a gmt5 branch. Ping me when you create a PR for it.

**Comment by seisman** [comment]
Now the v5.x branch builds GMT5 and uploads the binary packages with the "main" label.

It seems we can have both master and v5.x branch with the "main" label, and users can install GMT6 by:
```
conda install gmt
```
and GMT5 by:
```
conda install gmt=5
```

No need to have a gmt5 label as described in my first comment.

**Comment by ocefpaf** [comment]
Yep. Labels are only for dev releases. Stable versions can be handled by
constraints.

**Comment by seisman** [comment]
OK, closed.
